//spring.application.name=security
spring.datasource.url=jdbc:postgresql://localhost:5432/Burhan
spring.datasource.username=postgres
spring.datasource.password=2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true